name: Rectify11

on:
  workflow_dispatch:
  push:
  pull_request:
  workflow_run:
    workflows: ["Submodules Sync"]
    types:
      - completed

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_CERT_REVOCATION_MODE: offline
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4.1.1
      with: 
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive
        lfs: true

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      
    - name: Restore NuGet Packages
      run: nuget restore Rectify11Installer.sln || true  # Ignore errors and continue

    - name: Build
      run: msbuild Rectify11Installer.sln /p:Configuration=Release /p:platform=x64 /p:ContinueOnError=true || true  # Ignore errors and continue

    - name: Create single exe
      run: Rectify11Installer\ILRepack.exe Rectify11Installer\bin\Release\Rectify11Installer.exe /out:Rectify11Installer\bin\output\Release\Rectify11Installer.exe Rectify11Installer\bin\Release\libmsstyle.dll Rectify11Installer\bin\Release\TaskDialog.dll || true  # Ignore errors and continue
      
    - name: Upload Rectify11Installer
      uses: actions/upload-artifact@v4.3.1
      with:
        name: Rectify11Installer (x64)
        path: Rectify11Installer\bin\output\Release\Rectify11Installer.exe
        compression-level: 0
